### ISSUE TITLE
Fails to start on Fedora 19

### ISSUE THREAD

**Issue by ciupicri** [suzanshakya/nginx-server#1]
```
[ciupicri@hermes test]$ python ~/3rdparty-projects/nginx-server/nginx-server.py 
'/tmp/test' serving in 'http://localhost:8000'
nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
2013/11/06 23:49:21 [emerg] 31979#0: open() "/usr/local/etc/nginx/mime.types" failed (2: No such file or directory) in /tmp/nginx.conf:9
[ciupicri@hermes test]$ rpm -q nginx
nginx-1.4.2-1.fc19.x86_64
```

**Comment by lost-theory** [comment]
I get the same error on ubuntu. Seems there is no way to workaround it.

http://wiki.nginx.org/CoreModule#error_log

> Also note that as of version 0.7.53, nginx will use a compiled-in default error log location until it has read the config file. If the user running nginx doesn't have write permission to this log location, nginx will raise an alert like this:
> [alert]: could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)

You have to run with sudo or make that directory writable for your user.

**Comment by suzanshakya** [comment]
Hi,
About `"/var/log/nginx/error.log" failed (13: Permission denied)`, I have set `error_log` to `stderr` in the nginx config file. With this, the `Permission denied` will still display in stderr, but the script will continue to run.

About `open() "/usr/local/etc/nginx/mime.types" failed (2: No such file or directory)`, if the default location doesn't exist, the script will now `locate` the `*/nginx/mime.types`. If still not found, the script won't include any mime types file, but the script will run.
